### ISSUE TITLE
BookmarksToFile Broken On Firefox (Latest Version) including Waterfox

### ISSUE THREAD

**Issue by jkun-stargus-sc1gus-2020s** [Rebel1898/BookmarksToFile#1]
Tried downloading a bookmarks folder or URL page file by converting to a ZIP file,
but suddenly - 22 byes would mean they are no folders or URL files stored in there sadly. :(
Therefore please update and fix BookmarksToFile so that the "Empty ZIP file" issue after downloading on there gets solved possibly.

Thanks in advance

Version of Firefox: 106.0.1 (64-bit)
Version of WaterFox (untested): G5.0.1 (64-bit)

**Comment by Rebel1898** [comment]
On my machine on Firefox 106.0.1 (64-bit) it is working properly for all cases.  Even if the folder has no bookmars inside, it is properly zipped and downloaded. Can you provide more info with the error? Is your console showing any error on it? Anything that can help to force this -22 bytes error.

**Comment by jkun-stargus-sc1gus-2020s** [comment]
> On my machine on Firefox 106.0.1 (64-bit) it is working properly for all cases. Even if the folder has no bookmars inside, it is properly zipped and downloaded. Can you provide more info with the error? Is your console showing any error on it? Anything that can help to force this -22 bytes error.

TRIED:
VERSION PER BROWSER:
Firefox: 106.0.2
Waterfox: G5.0.2

Download All = Does Nothing, meaning does not work at all
Downlaod Selected = Working But Only Downloads a 22 byte (instead of more than 22 byes, e.g 1mb) .ZIP file before viewing (e.g. Empty ZIP/RAR Contents, No URL Files to Folders Inside)

ERRORS FOUND WHILE IN DEBUGGER VIEW:
Uncaught TypeError: document.getElementById(...) is null = 159: document.getElementById('btn-save-selected').addEventListener("click", (e) => {
Uncaught (in promise) TypeError: descargartodo[15] is undefined (1/2) = (logItems)123: var rutafinal = writeparentpath(descargartodo[15].parentId, descargartodo, "");
Uncaught (in promise) TypeError: descargartodo[15] is undefined (2/2) = (logTree)238: logItems(bookmarkItems[0], 0);

Whatever version of both Firefox and Waterfox you are using or that I am using either working or not working,
I am sending attachments about the problem before you bug-error-fix-solving them and update the extension right away.

DOWNLOAD, CHECK AND VIEW THESE PLEASE
[Firefox106_BookmarksToFile_BeforeBug.zip](https://github.com/Rebel1898/BookmarksToFile/files/9890550/Firefox106_BookmarksToFile_BeforeBug.zip) - 5.71 KB (5,857 bytes)
[Firefox106_BookmarksToFile_AfterBug.zip](https://github.com/Rebel1898/BookmarksToFile/files/9890551/Firefox106_BookmarksToFile_AfterBug.zip) -22 bytes (22 bytes) = Empty ZIP File (No Folders, No Files, etc.)
[WaterfoxG502_BookmarksToFile_BeforeBug.zip](https://github.com/Rebel1898/BookmarksToFile/files/9890555/WaterfoxG502_BookmarksToFile_BeforeBug.zip) - 5.71 KB (5,857 bytes)
[WaterfoxG502_BookmarksToFile_AfterBug.zip](https://github.com/Rebel1898/BookmarksToFile/files/9890552/WaterfoxG502_BookmarksToFile_AfterBug.zip) - 22 bytes (22 bytes) = Empty ZIP File (No Folders, No Files, etc.)
DOWNLOAD, CHECK AND VIEW THESE PLEASE

Let me know after downloading, checking and viewing them carefully.

**Comment by jkun-stargus-sc1gus-2020s** [comment]
@Rebel1898 https://github.com/Rebel1898/BookmarksToFile/issues/1#issuecomment-1295251895

Extension's "Download All/Selected" buttons still broken plus not working since last months ago,
therefore I couldn't find any alternatives for BookmarksToFile via the addons.mozilla.org/en-us site sadly.

Just letting you know before future updates/fixes + reviewing the other comments here on Github, thx in advance! - ~jkun

**Comment by Rebel1898** [comment]
I was able to reproduce error on version 108.  New version will be deployed soon on firefox addons.
I will mark this issue as solved. 
@feruenzerujkun  Thank you very much for your feedback and interest. Hope new version performs sharply for you.
